inherit_from: .rubocop_todo.yml

# Métodos inicializadores. Mantidos para saber quais os argumentos
# possíveis.
Metrics/ParameterLists:
  Exclude:
    - '**/classe_vienna.rb'
    - '**/protocolo.rb'
